version: 2.1
jobs:
  gke_create_cluster:
    docker: 
      - image: ariv3ra/terraform-gcp:latest
    environment:
      CLOUDSDK_CORE_PROJECT: servian-tech-challenge
    steps:
      - checkout
      - run:
          name: Create GKE cluster
          command: |
            echo $TF_CLOUD_TOKEN | base64 -d > $HOME/.terraformrc
            echo $GOOGLE_CLOUD_KEYS | base64 -d > $HOME/gcloud_keys.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud_keys.json
            cd part03/iac_gke_cluster/
            terraform init
            terraform plan -out=plan.txt
            terraform apply plan.txt
    
workflows:
  build_test:
    jobs:
      - gke_create_cluster

