version: 2.1
jobs:
  gke_create_cluster:
    docker: 
      - image: ariv3ra/terraform-gcp:latest
    environment:
      CLOUDSDK_CORE_PROJECT: servian-tech-challenge
    steps:
      - checkout
      - run:
          name: Create GKE cluster
          command: |
            echo $TF_CLOUD_TOKEN | base64 -d > $HOME/.terraformrc
            echo $GOOGLE_CLOUD_KEYS | base64 -d > $HOME/gcloud_keys.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud_keys.json
            cd part03/iac_gke_cluster/
            terraform init
            terraform plan -var credentials=$HOME/gcloud_keys.json -out=plan.txt
            terraform apply plan.txt
            

  gke_deploy_app:
    docker: 
      - image: cimg/base:2020.10
    environment:
      CLOUDSDK_CORE_PROJECT: servian-tech-challenge
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - checkout
      - run:
          name: Deploy app on GKE
          command: |
            echo $GOOGLE_CLOUD_KEYS | base64 -d > $HOME/gcloud_keys.json
            curl https://sdk.cloud.google.com | bash > /dev/null;
            source $HOME/google-cloud-sdk/path.bash.inc
            gcloud components update kubectl
            gcloud auth activate-service-account --key-file=${HOME}/gcloud_keys.json
            gcloud config set project servian-tech-challenge
            gcloud config set compute/zone us-central1-a
            gcloud container clusters get-credentials servian-app-v2
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            # bash ./deploy.sh

  # gke_deploy_app:
  #   environment:
  #     CLOUDSDK_CORE_PROJECT: servian-tech-challenge
  #     CLOUDSDK_CORE_DISABLE_PROMPTS: 1
  #   machine: true
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy app on GKE
  #         command: |
  #           echo $GOOGLE_CLOUD_KEYS | base64 -d > $HOME/gcloud_keys.json
  #           curl https://sdk.cloud.google.com | bash > /dev/null;
  #           source $HOME/google-cloud-sdk/path.bash.inc
  #           gcloud components update kubectl
  #           gcloud auth activate-service-account --key-file=${HOME}/gcloud_keys.json
  #           gcloud config set project servian-tech-challenge
  #           gcloud config set compute/zone us-central1-a
  #           gcloud container clusters get-credentials servian-app-v2
  #           docker logout
  #           echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
  #           bash ./deploy.sh

workflows:
  build_test:
    jobs:
      - gke_create_cluster
      - gke_deploy_app:
          requires:
            - gke_create_cluster

